### ISSUE TITLE
[BUG] HttpMate client always adds a trailing slash, even to urls that end with somthing like tweet.json

### ISSUE THREAD

**Issue by staenker** [envimate/httpmate#19]
**Describe the bug**
HttpMate client always adds a trailing slash, even to urls that end with somthing like tweet.json. The moment query parameters are added, urls like tweet.json/?param=23 are being generated/used, instead, tweet.json?param=23 should be used

**To Reproduce**
try it out

**Expected behavior**
tweet.json?param=23

**Environment description**

* Project version used 
* 11

**Additional context**

**Comment by envimate-opensource** [comment]
Fixed, passing tests:
```
@Test
    public void clientDoesNotAppendATrailingSlashToPathToDirectory() {
        givenAnHttpServer()
                .when().aRequestIsMadeToThePath("/qwer")
                .theServerReceivedARequestToThePath("/qwer");
    }

    @Test
    public void clientDoesNotAppendATrailingSlashToPathToFile() {
        givenAnHttpServer()
                .when().aRequestIsMadeToThePath("/qwer/tweet.json")
                .theServerReceivedARequestToThePath("/qwer/tweet.json");
    }
```
