### ISSUE TITLE
[ISSUE] SimpleHttpResponseObject in HttpMateClient should have a toString method

### ISSUE THREAD

**Issue by staenker** [envimate/httpmate#21]
**Do you have an awesome idea to improve the project? Please describe.**
SimpleHttpResponseObject in HttpMateClient should have a toString method, next to a method called describe, which returns a nice representation of the response

**Is your feature request related to a problem? Please describe.**
SimpleHttpResponseObject is awesome for exploring WebAPIs but without the ability to print the response, SimpleHttpResponseObject can't be used for that purpose.

**Describe the solution you'd like**
SimpleHttpResponseObject should have a toString method, next to a method called describe, which returns a nice representation of the response

**Comment by envimate-opensource** [comment]
Fixed, now reads like:
```
SimpleHttpResponseObject(statusCode=200, headers={date=Fri, 15 Nov 2019 09:07:42 GMT, transfer-encoding=chunked}, body=)
```
For a more detailed/beautiful string representation, `describe()` can be called, which results in beautiful output like:
```
|===================================================|
|                   HTTP Response                   |
|===================================================|
| Status Code | 200                                 |
|---------------------------------------------------|
| Headers     | date = Fri, 15 Nov 2019 09:09:19 GMT|
|             | transfer-encoding = chunked         |
|---------------------------------------------------|
| Body        |                                     |
|---------------------------------------------------|
```
